# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# https://github.com/actions

name: Build/Deploy

on:
  push:
    paths:
      - 'src/**'
    branches:
      - 'master'
      - 'release'
      - 'develop'
      - 'feature'
      - 'hotfix'
      - 'master/**'
      - 'release/**'
      - 'develop/**'
      - 'feature/**'
      - 'hotfix/**'
  repository_dispatch:
    types: builddispatch
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup-dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Diagnostic print enviroment vars
      run: printenv

    - name: Display dotnet version
      run: dotnet --version    

    - name: Display powershell core version
      run: pwsh --version

    - name: Workflow Build/Deploy
      run: .github/workflows/build_deploy_new.ps1 "${{ secrets.PAT }}" "${{ secrets.NUGET_PAT }}" "${{ secrets.NUGET_TEST_PAT }}"
      shell: pwsh 
